ARG BASE_IMAGE=acr.aishu.cn/public/ubuntu:22.04.20251014
FROM ${BASE_IMAGE}

RUN mkdir -p /opt \
    && groupadd -g 5000 -f autoflow \
    && useradd autoflow -u 5000 -g 5000 -m -s /bin/bash \
    && mkdir -p /opt/flow-automation \
    && mkdir -p /opt/pipeline \
    && chown -R autoflow:autoflow /opt

COPY flow-automation/ /opt/flow-automation/
COPY pipeline/ /opt/pipeline/

RUN chmod +x /opt/flow-automation/flow-automation \
    && chmod +x /opt/pipeline/pipeline-mgmt-server \
    && chmod +x /opt/pipeline/pipeline-worker-server

USER autoflow

WORKDIR /opt/

CMD ["sleep", "infinity"]
