// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/discovery_task_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockDiscoveryTaskAccess is a mock of DiscoveryTaskAccess interface.
type MockDiscoveryTaskAccess struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoveryTaskAccessMockRecorder
}

// MockDiscoveryTaskAccessMockRecorder is the mock recorder for MockDiscoveryTaskAccess.
type MockDiscoveryTaskAccessMockRecorder struct {
	mock *MockDiscoveryTaskAccess
}

// NewMockDiscoveryTaskAccess creates a new mock instance.
func NewMockDiscoveryTaskAccess(ctrl *gomock.Controller) *MockDiscoveryTaskAccess {
	mock := &MockDiscoveryTaskAccess{ctrl: ctrl}
	mock.recorder = &MockDiscoveryTaskAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoveryTaskAccess) EXPECT() *MockDiscoveryTaskAccessMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDiscoveryTaskAccess) Create(ctx context.Context, task *interfaces.DiscoveryTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDiscoveryTaskAccessMockRecorder) Create(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDiscoveryTaskAccess)(nil).Create), ctx, task)
}

// GetByID mocks base method.
func (m *MockDiscoveryTaskAccess) GetByID(ctx context.Context, id string) (*interfaces.DiscoveryTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.DiscoveryTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDiscoveryTaskAccessMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDiscoveryTaskAccess)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockDiscoveryTaskAccess) List(ctx context.Context, params interfaces.DiscoveryTaskQueryParams) ([]*interfaces.DiscoveryTask, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.DiscoveryTask)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDiscoveryTaskAccessMockRecorder) List(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDiscoveryTaskAccess)(nil).List), ctx, params)
}

// UpdateProgress mocks base method.
func (m *MockDiscoveryTaskAccess) UpdateProgress(ctx context.Context, id string, progress int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProgress", ctx, id, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProgress indicates an expected call of UpdateProgress.
func (mr *MockDiscoveryTaskAccessMockRecorder) UpdateProgress(ctx, id, progress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProgress", reflect.TypeOf((*MockDiscoveryTaskAccess)(nil).UpdateProgress), ctx, id, progress)
}

// UpdateResult mocks base method.
func (m *MockDiscoveryTaskAccess) UpdateResult(ctx context.Context, id string, result *interfaces.DiscoveryResult, stime int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResult", ctx, id, result, stime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateResult indicates an expected call of UpdateResult.
func (mr *MockDiscoveryTaskAccessMockRecorder) UpdateResult(ctx, id, result, stime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResult", reflect.TypeOf((*MockDiscoveryTaskAccess)(nil).UpdateResult), ctx, id, result, stime)
}

// UpdateStatus mocks base method.
func (m *MockDiscoveryTaskAccess) UpdateStatus(ctx context.Context, id, status, message string, stime int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, message, stime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDiscoveryTaskAccessMockRecorder) UpdateStatus(ctx, id, status, message, stime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDiscoveryTaskAccess)(nil).UpdateStatus), ctx, id, status, message, stime)
}
