// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/discovery_worker.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	asynq "github.com/hibiken/asynq"
)

// MockDiscoveryWorker is a mock of DiscoveryWorker interface.
type MockDiscoveryWorker struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoveryWorkerMockRecorder
}

// MockDiscoveryWorkerMockRecorder is the mock recorder for MockDiscoveryWorker.
type MockDiscoveryWorkerMockRecorder struct {
	mock *MockDiscoveryWorker
}

// NewMockDiscoveryWorker creates a new mock instance.
func NewMockDiscoveryWorker(ctrl *gomock.Controller) *MockDiscoveryWorker {
	mock := &MockDiscoveryWorker{ctrl: ctrl}
	mock.recorder = &MockDiscoveryWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoveryWorker) EXPECT() *MockDiscoveryWorkerMockRecorder {
	return m.recorder
}

// ProcessTask mocks base method.
func (m *MockDiscoveryWorker) ProcessTask(ctx context.Context, event *asynq.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTask", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTask indicates an expected call of ProcessTask.
func (mr *MockDiscoveryWorkerMockRecorder) ProcessTask(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTask", reflect.TypeOf((*MockDiscoveryWorker)(nil).ProcessTask), ctx, event)
}

// Run mocks base method.
func (m *MockDiscoveryWorker) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockDiscoveryWorkerMockRecorder) Run(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockDiscoveryWorker)(nil).Run), ctx)
}

// Start mocks base method.
func (m *MockDiscoveryWorker) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockDiscoveryWorkerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockDiscoveryWorker)(nil).Start))
}
