// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/discovery_task_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockDiscoveryTaskService is a mock of DiscoveryTaskService interface.
type MockDiscoveryTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoveryTaskServiceMockRecorder
}

// MockDiscoveryTaskServiceMockRecorder is the mock recorder for MockDiscoveryTaskService.
type MockDiscoveryTaskServiceMockRecorder struct {
	mock *MockDiscoveryTaskService
}

// NewMockDiscoveryTaskService creates a new mock instance.
func NewMockDiscoveryTaskService(ctrl *gomock.Controller) *MockDiscoveryTaskService {
	mock := &MockDiscoveryTaskService{ctrl: ctrl}
	mock.recorder = &MockDiscoveryTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoveryTaskService) EXPECT() *MockDiscoveryTaskServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDiscoveryTaskService) Create(ctx context.Context, catalogID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, catalogID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDiscoveryTaskServiceMockRecorder) Create(ctx, catalogID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDiscoveryTaskService)(nil).Create), ctx, catalogID)
}

// GetByID mocks base method.
func (m *MockDiscoveryTaskService) GetByID(ctx context.Context, id string) (*interfaces.DiscoveryTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.DiscoveryTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDiscoveryTaskServiceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDiscoveryTaskService)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockDiscoveryTaskService) List(ctx context.Context, params interfaces.DiscoveryTaskQueryParams) ([]*interfaces.DiscoveryTask, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.DiscoveryTask)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDiscoveryTaskServiceMockRecorder) List(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDiscoveryTaskService)(nil).List), ctx, params)
}

// UpdateResult mocks base method.
func (m *MockDiscoveryTaskService) UpdateResult(ctx context.Context, id string, result *interfaces.DiscoveryResult, stime int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResult", ctx, id, result, stime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateResult indicates an expected call of UpdateResult.
func (mr *MockDiscoveryTaskServiceMockRecorder) UpdateResult(ctx, id, result, stime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResult", reflect.TypeOf((*MockDiscoveryTaskService)(nil).UpdateResult), ctx, id, result, stime)
}

// UpdateStatus mocks base method.
func (m *MockDiscoveryTaskService) UpdateStatus(ctx context.Context, id, status, message string, stime int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, message, stime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDiscoveryTaskServiceMockRecorder) UpdateStatus(ctx, id, status, message, stime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDiscoveryTaskService)(nil).UpdateStatus), ctx, id, status, message, stime)
}
