server:
  runMode: release
  httpPort: 13014
  language: zh-CN
  readTimeOut: 600
  writeTimeOut: 600
log:
  logLevel: info
  developMode: false
  maxAge: 100
  maxBackups: 20
  maxSize: 100
crypto:
  enabled: true
  privateKeyPath: /opt/vega-backend/secret-config/rsa_private_key_pkcs8.pem
  publicKeyPath: /opt/vega-backend/secret-config/rsa_public_key.pem
depServices:
  class-443:
    ingressClass: class-443
  rds:
    host: mariadb-mariadb-master.resource.svc.cluster.local.
    port: 3330
    user: username
    password: password
    type: MariaDB
  mq:
    mqType: kafka
    mqHost: kafka-headless.resource.svc.cluster.local.
    mqPort: 9092
    protocol: sasl_plaintext
    tenant: default
    auth:
      username: username
      password: password
      mechanism: PLAIN
  opensearch:
    host: localhost
    port: 9200
    protocol: http
    username: username
    password: password
  redis:
    connecttype: ""
    username: ""
    password: ""
    host: ""
    port: 0
    masterhost: ""
    masterport: 0
    slavehost: ""
    slaveport: 0
    sentinelhost: ""
    sentinelport: 0
    sentinelusername: ""
    sentinelpassword: ""
    mastergroupname: ""
  authorization-private:
    host: authorization-private
    port: 30920
    protocol: http
  user-management:
    host: user-management-private
    port:  30980
    protocol: http
  hydra-admin:
    host: hydra-admin
    port: 4445
    protocol: http
