// Code generated by MockGen. DO NOT EDIT.
// Source: logics_skill.go
//
// Generated by this command:
//
//	mockgen -source=logics_skill.go -destination=../mocks/logics_skill.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/kweaver-ai/adp/execution-factory/operator-integration/server/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockSkillRegistry is a mock of SkillRegistry interface.
type MockSkillRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockSkillRegistryMockRecorder
	isgomock struct{}
}

// MockSkillRegistryMockRecorder is the mock recorder for MockSkillRegistry.
type MockSkillRegistryMockRecorder struct {
	mock *MockSkillRegistry
}

// NewMockSkillRegistry creates a new mock instance.
func NewMockSkillRegistry(ctrl *gomock.Controller) *MockSkillRegistry {
	mock := &MockSkillRegistry{ctrl: ctrl}
	mock.recorder = &MockSkillRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillRegistry) EXPECT() *MockSkillRegistryMockRecorder {
	return m.recorder
}

// DeleteSkill mocks base method.
func (m *MockSkillRegistry) DeleteSkill(ctx context.Context, req *interfaces.DeleteSkillReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSkill", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSkill indicates an expected call of DeleteSkill.
func (mr *MockSkillRegistryMockRecorder) DeleteSkill(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSkill", reflect.TypeOf((*MockSkillRegistry)(nil).DeleteSkill), ctx, req)
}

// GetSkillDetail mocks base method.
func (m *MockSkillRegistry) GetSkillDetail(ctx context.Context, req *interfaces.GetSkillDetailReq) (*interfaces.SkillInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkillDetail", ctx, req)
	ret0, _ := ret[0].(*interfaces.SkillInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkillDetail indicates an expected call of GetSkillDetail.
func (mr *MockSkillRegistryMockRecorder) GetSkillDetail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkillDetail", reflect.TypeOf((*MockSkillRegistry)(nil).GetSkillDetail), ctx, req)
}

// QuerySkillList mocks base method.
func (m *MockSkillRegistry) QuerySkillList(ctx context.Context, req *interfaces.QuerySkillListReq) (*interfaces.QuerySkillListResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySkillList", ctx, req)
	ret0, _ := ret[0].(*interfaces.QuerySkillListResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuerySkillList indicates an expected call of QuerySkillList.
func (mr *MockSkillRegistryMockRecorder) QuerySkillList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySkillList", reflect.TypeOf((*MockSkillRegistry)(nil).QuerySkillList), ctx, req)
}

// RegisterSkill mocks base method.
func (m *MockSkillRegistry) RegisterSkill(ctx context.Context, req *interfaces.RegisterSkillReq) (*interfaces.RegisterSkillResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterSkill", ctx, req)
	ret0, _ := ret[0].(*interfaces.RegisterSkillResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterSkill indicates an expected call of RegisterSkill.
func (mr *MockSkillRegistryMockRecorder) RegisterSkill(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterSkill", reflect.TypeOf((*MockSkillRegistry)(nil).RegisterSkill), ctx, req)
}

// MockSkillReader is a mock of SkillReader interface.
type MockSkillReader struct {
	ctrl     *gomock.Controller
	recorder *MockSkillReaderMockRecorder
	isgomock struct{}
}

// MockSkillReaderMockRecorder is the mock recorder for MockSkillReader.
type MockSkillReaderMockRecorder struct {
	mock *MockSkillReader
}

// NewMockSkillReader creates a new mock instance.
func NewMockSkillReader(ctrl *gomock.Controller) *MockSkillReader {
	mock := &MockSkillReader{ctrl: ctrl}
	mock.recorder = &MockSkillReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillReader) EXPECT() *MockSkillReaderMockRecorder {
	return m.recorder
}

// GetSkillGuide mocks base method.
func (m *MockSkillReader) GetSkillGuide(ctx context.Context, req *interfaces.GetSkillGuideReq) (*interfaces.GetSkillGuideResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkillGuide", ctx, req)
	ret0, _ := ret[0].(*interfaces.GetSkillGuideResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkillGuide indicates an expected call of GetSkillGuide.
func (mr *MockSkillReaderMockRecorder) GetSkillGuide(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkillGuide", reflect.TypeOf((*MockSkillReader)(nil).GetSkillGuide), ctx, req)
}

// ReadSkillFile mocks base method.
func (m *MockSkillReader) ReadSkillFile(ctx context.Context, req *interfaces.ReadSkillFileReq) (*interfaces.ReadSkillFileResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSkillFile", ctx, req)
	ret0, _ := ret[0].(*interfaces.ReadSkillFileResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSkillFile indicates an expected call of ReadSkillFile.
func (mr *MockSkillReaderMockRecorder) ReadSkillFile(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSkillFile", reflect.TypeOf((*MockSkillReader)(nil).ReadSkillFile), ctx, req)
}

// MockSkillRuntimeBinder is a mock of SkillRuntimeBinder interface.
type MockSkillRuntimeBinder struct {
	ctrl     *gomock.Controller
	recorder *MockSkillRuntimeBinderMockRecorder
	isgomock struct{}
}

// MockSkillRuntimeBinderMockRecorder is the mock recorder for MockSkillRuntimeBinder.
type MockSkillRuntimeBinderMockRecorder struct {
	mock *MockSkillRuntimeBinder
}

// NewMockSkillRuntimeBinder creates a new mock instance.
func NewMockSkillRuntimeBinder(ctrl *gomock.Controller) *MockSkillRuntimeBinder {
	mock := &MockSkillRuntimeBinder{ctrl: ctrl}
	mock.recorder = &MockSkillRuntimeBinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillRuntimeBinder) EXPECT() *MockSkillRuntimeBinderMockRecorder {
	return m.recorder
}

// ListAgentSkills mocks base method.
func (m *MockSkillRuntimeBinder) ListAgentSkills(ctx context.Context, req *interfaces.AgentSkillBindingReq) (*interfaces.AgentSkillBindingResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentSkills", ctx, req)
	ret0, _ := ret[0].(*interfaces.AgentSkillBindingResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgentSkills indicates an expected call of ListAgentSkills.
func (mr *MockSkillRuntimeBinderMockRecorder) ListAgentSkills(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentSkills", reflect.TypeOf((*MockSkillRuntimeBinder)(nil).ListAgentSkills), ctx, req)
}
