// Code generated by MockGen. DO NOT EDIT.
// Source: asset_store.go
//
// Generated by this command:
//
//	mockgen -source=asset_store.go -destination=../../mocks/skill_asset_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockskillAssetStore is a mock of skillAssetStore interface.
type MockskillAssetStore struct {
	ctrl     *gomock.Controller
	recorder *MockskillAssetStoreMockRecorder
	isgomock struct{}
}

// MockskillAssetStoreMockRecorder is the mock recorder for MockskillAssetStore.
type MockskillAssetStoreMockRecorder struct {
	mock *MockskillAssetStore
}

// NewMockskillAssetStore creates a new mock instance.
func NewMockskillAssetStore(ctrl *gomock.Controller) *MockskillAssetStore {
	mock := &MockskillAssetStore{ctrl: ctrl}
	mock.recorder = &MockskillAssetStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockskillAssetStore) EXPECT() *MockskillAssetStoreMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockskillAssetStore) DeleteFile(ctx context.Context, storageKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, storageKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockskillAssetStoreMockRecorder) DeleteFile(ctx, storageKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockskillAssetStore)(nil).DeleteFile), ctx, storageKey)
}

// DeleteSkill mocks base method.
func (m *MockskillAssetStore) DeleteSkill(ctx context.Context, skillID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSkill", ctx, skillID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSkill indicates an expected call of DeleteSkill.
func (mr *MockskillAssetStoreMockRecorder) DeleteSkill(ctx, skillID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSkill", reflect.TypeOf((*MockskillAssetStore)(nil).DeleteSkill), ctx, skillID)
}

// Read mocks base method.
func (m *MockskillAssetStore) Read(ctx context.Context, storageKey string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, storageKey)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockskillAssetStoreMockRecorder) Read(ctx, storageKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockskillAssetStore)(nil).Read), ctx, storageKey)
}

// Write mocks base method.
func (m *MockskillAssetStore) Write(ctx context.Context, skillID, relPath string, content []byte) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, skillID, relPath, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Write indicates an expected call of Write.
func (mr *MockskillAssetStoreMockRecorder) Write(ctx, skillID, relPath, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockskillAssetStore)(nil).Write), ctx, skillID, relPath, content)
}
